language: go
go:
  - master
before_install:
  - go get -t -v ./...
install:
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
